In [18]:
import numpy as np 
import math

In [19]:
a1 = np.array([
    [155, 221, 289, 0, 72, 143],
    [59, 24, 52, 45, 10, 1]
])

a2 = np.array([
    [35, 101, 169, 240, 312, 23],
    [0, 30, 56, 43, 5, 6]
])

a2_a1 = np.array([
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0]
    ])

for i in range(0,6):
    a2_a1[0][i] = a2[0][i] - a1[0][i]
    a2_a1[1][i] = a2[1][i] - a1[1][i]
print(a2_a1) 

[[-120 -120 -120  240  240 -120]
 [ -59    6    4   -2   -5    5]]


In [20]:
b1 = np.array([
    [335, 41, 109, 180, 252, 323],
    [56, 25, 55, 43, 2, 3]
])

b2 = np.array([
    [215, 281, 349, 60, 132, 203],
    [57, 23, 52, 14, 7, 3]
])

b2_b1 = np.array([
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0]
    ])

for i in range(0,6):
    b2_b1[0][i] = b2[0][i] - b1[0][i]
    b2_b1[1][i] = b2[1][i] - b1[1][i]
print(b2_b1) 

[[-120  240  240 -120 -120 -120]
 [   1   -2   -3  -29    5    0]]


In [21]:
theta = np.array([
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0]
    ])
for i in range(0,6):
    theta[0][i] = a2_a1[0][i] + b2_b1[0][i]
    theta[1][i] = a2_a1[1][i] + b2_b1[1][i]
print(theta) 

[[-240  120  120  120  120 -240]
 [ -58    4    1  -31    0    5]]


In [24]:
A = np.array([
    [59, 60, 60, 59, 60, 59],
    [31, 2, 0.5, 44.5, 0, 57.5]
    ])

for i in range(0,6):
    A[0][i] += A[1][i] / 60
print(A) 

sum = 0
for i in A[0]:
    sum += i
print(sum / 6)

sum = 0
for i in A[0]:
    sum += (i - 59.87638888888889) * (i - 59.87638888888889)
print(math.sqrt(sum / 30))

[[59.51666667 60.03333333 60.00833333 59.74166667 60.         59.95833333]
 [31.          2.          0.5        44.5         0.         57.5       ]]
59.87638888888889
0.08398127730793103


In [26]:
math.sqrt(0.0839813 * 0.0839813 + 0.00481125 * 0.00481125)

0.08411900425143237

In [29]:
a1 = np.array([
    [133, 208, 285],
    [59, 32, 34]
])

a2 = np.array([
    [80, 154, 231],
    [20, 57, 55]
])

a2_a1 = np.array([
    [0, 0, 0],
    [0, 0, 0]
    ])

for i in range(0,3):
    a2_a1[0][i] = a2[0][i] - a1[0][i]
    a2_a1[1][i] = a2[1][i] - a1[1][i]
print(a2_a1) 

#============================================
b1 = np.array([
    [313, 28, 105],
    [58, 39, 41]
])

b2 = np.array([
    [260, 334, 51],
    [14, 57, 58]
])

b2_b1 = np.array([
    [0, 0, 0],
    [0, 0, 0]
    ])

for i in range(0,3):
    b2_b1[0][i] = b2[0][i] - b1[0][i]
    b2_b1[1][i] = b2[1][i] - b1[1][i]
print(b2_b1) 
#============================================


[[-53 -54 -54]
 [-39  25  21]]
[[-53 306 -54]
 [-44  18  17]]


In [33]:
delta_m = np.array([
    [0, 0, 0],
    [0, 0, 0]
    ])
for i in range(0,3):
    delta_m[0][i] = a2_a1[0][i] + b2_b1[0][i]
    delta_m[1][i] = a2_a1[1][i] + b2_b1[1][i]
print(delta_m)

delta_m2 = np.array([
    [-106, 252, -108],
    [-83.0, 43.0, 38.0]
    ])

for i in range(0,3):
    delta_m2[0][i] += delta_m2[1][i] / 60
print(delta_m2) 

for i in delta_m2[0]:
    print(i/2)

[[-106  252 -108]
 [ -83   43   38]]
[[-107.38333333  252.71666667 -107.36666667]
 [ -83.           43.           38.        ]]
-53.69166666666667
126.35833333333333
-53.68333333333333


In [34]:
180 - 126.35833333333333

53.641666666666666

In [36]:
delta_m3 = [53.69167, 53.64167, 53.68333]

for i in delta_m3:
    print(np.sin(np.radians((59.88 + i)/2)) / np.sin(np.radians(59.88/2)))

1.6762992212079861
1.6758201732123679
1.6762193381767916


In [37]:
(1.67630+1.67582+1.67622)/3

1.6761133333333333